const blessingsData = {
  id : 0,
  name : "LoreRim v2.2.8",
  
  blessings : [
    "None",
	"&#8212 Divines &#8212",
    "Akatosh",
    "Arkay",
    "Auriel",
    "Dibella",
    "Julianos",
    "Kynareth",
    "Mara",
    "Nocturnal",
    "Stendarr",
    "Talos",
    "Zenithar",
	"&#8212 Daedric Princes &#8212",
	"Azura",
	"Boethia",
	"Clavicus Vile",
	"Hermaeus Mora",
	"Hircine",
	"Jyggalag",
	"Malacath",
	"Mehrunes Dagon",
	"Mephala",
	"Meridia",
	"Molag Bal",
	"Namira",
	"Nocturnal",
	"Peryite",
	"Sanguine",
	"Sheogorath",
	"Vaermina",
	"&#8212 Elven Ancestors &#8212",
	"Auriel",
	"Jephre",
	"Magnus",
	"Phnaster",
	"Syrabane",
	"Trinimac",
	"Xarxes",
	"Z'en",
	"&#8212 Dunmer Tribunal &#8212",
	"Almalexia",
	"Sotha Sil",
	"Vivec",
	"&#8212 Yokudan Pantheon &#8212",
	"Leki",
	"Morwha",
	"Satakal",
	"Tall Papa",
	"The HoonDing",
	"&#8212 Khajiiti Pantheon &#8212",
	"Rajhin",
	"Riddle'Thar",
	"&#8212 Miscellaneous &#8212",
	"Baan Dar",
	"Ebonarm",
	"Mannimarco",
	"Sithis",
	"Shor",
	"St. Alessia",
	"The All-Maker",
	"The Hist",
	"The Magna-Ge",
	"The Old Ways"
  ]
};

addBlessingsData(blessingsData);

